# theme = "gruvbox"
# theme = "catppuccin_latte"
# theme = "onelight"
theme = "dracula"

[editor]
mouse = true
auto-format = true
auto-save = true
line-number = "relative"
bufferline = "always"
indent-guides.render = true
cursorline = true
color-modes = true
true-color = true
auto-pairs = false

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"A-h" = "move_char_left"
"A-j" = "move_line_down"
"A-k" = "move_line_up"
"A-l" = "move_char_right"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"A-c" = ":clipboard-yank"
"A-v" = ":clipboard-paste-replace"
"A-w" = [":write", ":line-ending lf"]
"A-q" = ":buffer-close!"
"A-n" = ":new"
"A-h" = ":buffer-previous"
"A-l" = ":buffer-next"
"A-left" = ":buffer-previous"
"A-right" = ":buffer-next"
"A-g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
g = { a = "code_action" }
C-f = [
  ":new",
  ":insert-output lf-pick",
  ":theme default",
  "select_all",
  "split_selection_on_newline",
  "goto_file",
  "goto_last_modified_file",
  ":buffer-close!",
  ":theme onelight",
]

#"space" = { "t" = ":sh wezterm cli split-pane --bottom --percent 30 --cwd $(pwd)"}
