[[language]]
name = "python"
language-servers = [ "pyright" ]
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}


[[language]]
name = "yaml"
auto-format = true
formatter = {command = 'prettier', args = ["--parser", "yaml"]}

[[language]]
name = "markdown"
auto-format = true
formatter = {command = 'prettier', args = ["--parser", "markdown"]}

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
[language.debugger]
command = "dlv"
name = "dlv"
port-arg = "--port {}"
transport = "tcp"
[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"
[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

